# import the lib

In [1]:
import numpy as np

# scalars

In [2]:
s=5
s

5

# vector

In [3]:
v=np.array([1,-2,3])

In [4]:
v

array([ 1, -2,  3])

# matrix

In [10]:
m=np.array([[1,2,3],
            [3,2,1]])
m

array([[1, 2, 3],
       [3, 2, 1]])

# Data type


In [11]:
type(s)

int

In [12]:
type(v)

numpy.ndarray

In [13]:
type(m)

numpy.ndarray

In [14]:
s_array=np.array(5)
s_array

array(5)

# shape

In [18]:
m.shape

(2, 3)

In [16]:
type(s_array)

numpy.ndarray

In [19]:
v.shape

(3,)

In [21]:
s_array.shape

()

# reshape

In [22]:
v.reshape([1,3])

array([[ 1, -2,  3]])

In [23]:
v.reshape([3,1])

array([[ 1],
       [-2],
       [ 3]])