In [1]:
import numpy as np

In [2]:
m1=np.array([[1,2,3],[4,5,6]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
m2=np.array([[7,8,9],[3,2,1]])
m2

array([[7, 8, 9],
       [3, 2, 1]])

# crearting tensor

In [4]:
t=np.array([m1,m2])
t

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 2, 1]]])

# shape

In [5]:
t.shape

(2, 2, 3)